#!/usr/bin/env php
<?php

define('GATEWAY_ROOT', __DIR__);

require GATEWAY_ROOT.'/vendor/autoload.php';

use Elastica\Client;
use KejawenLab\SemartApiGateway\Gateway;
use KejawenLab\SemartApiGateway\Server\RequestFactory;
use KejawenLab\SemartApiGateway\Server\ResponseFactory;
use Swoole\HTTP\Server;
use Symfony\Component\Dotenv\Dotenv;
use Symfony\Component\HttpFoundation\Request;

if (!isset($_SERVER['SEMART_ENV']) || !isset($_SERVER['SEMART_REDIST_HOST'])) {
    $dotEnv = new Dotenv();
    $dotEnv->load(sprintf('%s/.env', GATEWAY_ROOT));
}

$redis = new Redis();
$redis->connect($_SERVER['SEMART_REDIST_HOST'], $_SERVER['SEMART_REDIST_PORT']);

$elasticsearch = new Client(['host' => $_SERVER['SEMART_ELASTICSEARCH_HOST'], 'port' => $_SERVER['SEMART_ELASTICSEARCH_PORT']]);

$swoole = new Server('0.0.0.0', 9501);
$swoole->on('start', function ($server) {
    echo 'Swoole http server is started at http://127.0.0.1:9501'.PHP_EOL;
});

$swoole->on('request', function ($request, $response) use ($redis, $elasticsearch) {
    $app = new Gateway($redis, $elasticsearch, $_SERVER['SEMART_ENV']);

    $GLOBALS['app'] = $app;

    ResponseFactory::process($response, $app->handle(RequestFactory::toSymfonyRequest($request)));
});

$swoole->start();
